### ISSUE TITLE
how to select for hiv data?

### ISSUE THREAD

**Issue by liamxg** [niemasd/FAVITES-Lite#13]
<img width="541" alt="image" src="https://github.com/niemasd/FAVITES-Lite/assets/46078579/b821e343-47d9-4a88-8612-53bd097ca81b">

**Comment by niemasd** [comment]
I unfortunately cannot help with designing your model: you will need to do literature search to see what models are reasonable assumptions to make about your specific virus + population. I can only help debug the tool itself

**Comment by liamxg** [comment]
ok, got it.
