### ISSUE TITLE
Add "Import" button

### ISSUE THREAD

**Issue by niemasd** [niemasd/FAVITES-Lite#5]
It would be good to have an "Import" button (ideally immediately to the left of the "Export" button in the header) that allows someone to import an existing FAVITES-Lite Config file (so they can pick up where they left off)

**Comment by niemasd** [comment]
@CatFish47 Do you think you could look into adding this functionality?

**Comment by niemasd** [comment]
Initial functionality added in https://github.com/niemasd/FAVITES-Lite/pull/9

Needs descriptive error when user attempts to import an invalid config JSON

**Comment by niemasd** [comment]
@CatFish47 When I imported the example config JSON, the modules and parameters loaded, but the colors in the left panel didn't update until I clicked elsewhere. Can you have it update the colors instantly upon loading?

**Comment by CatFish47** [comment]
I upgraded the import module a little bit in PR #10 . Let me know if you have any questions / any other wanted changes!

**Comment by niemasd** [comment]
Looks great, thank you!! One last minor thing that might be nice to add: when you click "IMPORT" and see the two import options, can we add a third import option at the bottom that's "Import Example File" which loads whatever file is at the following URL?

https://github.com/niemasd/FAVITES-Lite/raw/main/example/example.json

E.g. something that looks like this:

<img width="282" alt="screen" src="https://user-images.githubusercontent.com/4195510/233110120-101bee54-e849-48a0-848d-2bfb01b00aa0.png">

**Comment by niemasd** [comment]
Closing since this feature isn't strictly necessary (the user can just download the example file and open it)
